### ISSUE TITLE
How to set font size ?

### ISSUE THREAD

**Issue by kaosat-dev** [jkb0o/belly#30]
Hi ! 
Belly is really nice already very pleasant to use, but how can you set the font size ?
I tried using `font_size` in an ess file but I get `Error: Unsupported property: font_size` 
I looked through the code & the docs but could not find anything.
thanks in advance !

**Comment by jkb0o** [comment]
Property names follows kebab-case naming convention, like in css. Use `font-size` to specify font size:
```rust
/// eml:
commands.add(eml!(<span s:font-size="42px">Hello</span>))
```
```css
/* style.ess */

/* set font size to exact element */
span {
  font-size: 42px
}

/* 
  text elements often resides as children of other nodes,
  so it may be useful to set font props using `*` selector
*/

/* set default font size */
* {
  font-size: 24px
}
/* set font size for specific block
.specific-block * {
  font-size: 36px
}
```

There also orher font related properties:
```css
* {
  /* load custom font from assets folder */
  font: "fonts/MyFont.ttf"
  
  /* use predefined font style */
  font: bold /* regular|bold|italic|bold-italic */
  
  /* specify font color */
  color: red
}
```

I'd like to keep this issue open, until #31 got resolved.

**Comment by kaosat-dev** [comment]
Thanks a lot for your quick reply !
My bad also,  I was so focused on Bevy's text attributes that I forgot to try it css style :)
That is valuable information about using a specific font as well , thanks !

It is not really an issue at this stage but would there be any way of reusing a font specified in an asset file in `bevy_asset_loader` ? 

#31  is a very good idea !

Btw I have a list of other questions , possible bugs (still need to some testing outside of my main project to isolate things) , and (small) feature requests: is that too much at the current time or are you ok with that ?

Either way, thanks a lot for creating `Belly` , very useful and promising!

**Comment by jkb0o** [comment]
Thank you for such a words! I appreciate it!
> It is not really an issue at this stage but would there be any way of reusing a font specified in an asset file in bevy_asset_loader ?

I'm not sure if I understand you question right. Lets look on this ess:
```css
* {
  font: "my-font.ttf"
}
```
The `Text` components generated by belly will hold `Handle<Font>` to `my-font.ttf` asset. If you define same font in `bevy_asset_loader` asset, your asset collections will hold the same `Handle<Font>` to the same `my-font.ttf`, so it will be the only instance of `my-font.ttf` asset. 

You may want to pass font by asset key:
```css
* {
  font: "collection.assets#my.font"
}
```
Unfortunately for now it is not possible, but may be possible in future. 

> Btw I have a list of other questions , possible bugs (still need to some testing outside of my main project to isolate things) , and (small) feature requests: is that too much at the current time or are you ok with that ?

Fill free to contact me in discord [@jkbo#2629](https://discordapp.com/users/585419328716013568), or/and add issues. There are should be a lot of small bugs which is pretty easy to fix. Feature requests are welcome as well!
