### ISSUE TITLE
Implement layout-control widgets (`<row>`/`<column>`/`<center>`/`<wrap>`).

### ISSUE THREAD

**Issue by jkb0o** [jkb0o/belly#40]
For now there are only subset of html widgets implemented. When I wrote examples, I constantly lacked an easy way to define the layout (like put this in the center, and this in row, etc). It looks pretty useful to provide out-of-the box layout widgets with predefined styles:

- `<center>` places children in the center. Possible defaults:
```css
center {
  justify-content: center;
  align-content: center;
}
``` 
- `<row>` places children in a row. Possible defaults:
```css
row {
  flex-direction: row;
  justify-content: space-around;
  align-content: center;
}
```
- `<column>` places children in a column. Possible defaults:
```css
column {
  flex-direction: row;
  justify-content: space-around;
  align-content: center;
}
```
- `<wrap>` places children wrapped. Possible defaults:
```css
column {
  flex-wrap: wrap;
}
```

`row`/`column` widgets should provide the way to control main/opposite axis behaviour with attributes. 

To control main-axis behaviour I suggest to use "space" attribute (where to put spaces on the main axis):
```
<row space="between">...</row>
```
The possible values are:
- `around` for `JustifyContent::SpaceAround`
- `between` for `JustifyContent::SpaceBetween`
- `even` for `JustifyContent::SpaceEvenly`
- `end` for `JustifyContent::FlexStart`
- `start` for `JustifyContent::FlexEnd`
- `outside` for `JustifyContent::Center`

To control opposite-axis behaviour I suggest to use "align" attribute:
```
<column space="start" align="center">...</row>
```
- `space-around` for `AlignContent::SpaceAround`
- `space-between` for `AlignContent::SpaceBetween`
- `space-even` for `JustifyContent::SpaceEvenly`
- `start` for `JustifyContent::FlexStart`
- `end` for `JustifyContent::FlexEnd`
- `center` for `JustifyContent::Center`

I don't what attributes should be provided for `<center>`/`<wrap>`. Suggest and argue or left them empty.

It would be cool if the widget attributes turned out to be bindable and manageble (imposible to change via ess).

The complex examples (`color-picker`, `image`) and README should be taken into account (edit examples/readme to use this widgets).
